### ISSUE TITLE
Discovery Http Clients with installed Mock clients issue

### ISSUE THREAD

**Issue by ixarlie** [rpkamp/mailhog-behat-extension#56]
Hi, I've recently upgraded from v0.6.7 to v1.3.0 and noticed that the HTTP client discovery mechanism was changed from `php-http/discovery` to `psr-discovery/*` (as of v1.2.0)

In my project, I use `php-http/mock-client` because some of our services need to be mocked depending on the environment.

In v0.6.7, the `php-http/discovery` package did not automatically select `php-http/mock-client`, which allowed our Behat to pass as expected.

However, the new `psr-discovery/*` packages prioritize mocking clients like `php-http/mock-client`, even if the package is in `require-dev`.
https://github.com/psr-discovery/http-client-implementations?tab=readme-ov-file#mocking-priority

This change is causing Behat tests to fail, making it a blocking issue for us.

According to `psr-discovery/*` documentation, it is possible to prefer a specific implementation
https://github.com/psr-discovery/http-client-implementations?tab=readme-ov-file#preferring-an-implementation

The current version of this extension does not offer a way to define such a preference. It would be useful if the extension supported optional configuration to specify preferred implementations, for example:

```yaml
extensions:
    rpkamp\Behat\MailhogExtension:
            base_url: http://localhost:8025
            purge_tag: email
            discover-http-client: 'symfony/http-client'
            discover-http-message-factory: 'nyholm/psr7'
            discover-http-stream-factory: 'nyholm/psr7'
```

An alternative approach could be to rely on `symfony/http-client` implementations, since it is already a required (non-dev) dependency of this package (I don't know if having `symfony/http-client` in `require` was intentional)

Currently, I'm using the decorator pattern to wrap `MailhogExtension` (which is marked as final) in order to set a preferred client implementation before the container is loaded.

```php
final class DecoratedMailhogExtension implements Extension
{
    private readonly MailhogExtension $delegate;

    public function __construct()
    {
        $this->delegate = new MailhogExtension();
    }

    public function load(ContainerBuilder $container, array $config)
    {
        // Set preferred client to prevent selection of php-http/mock-client
        Clients::candidates();
        Clients::prefer('symfony/http-client');

        $this->delegate->load($container, $config);
    }

    // ... rest of methods ...
```

I can work on either approach and open a pull request.

Thanks
